name: Code Lint
description: 'Uses ktlint to verify code is formatted'

inputs:
  ktlint_version:
    description: 'The version of ktlint to use'
    required: true
  java_version:
    description: 'The version of java to use'
    required: true

runs:
  using: composite
  steps:
    - name: Java Setup
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'zulu'
        java-version: ${{ inputs.java_version }}
    - name: Download ktlint
      shell: bash
      run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/${{ inputs.ktlint_version }}/ktlint && chmod a+x ktlint
    - name: Run ktlint Android
      shell: bash
      run: |
        ./ktlint "**/src/**/*.kt" "!**/generated/**" --android --reporter=plain?group_by_file
