name: Execute Gradle Command
description: 'Setup Java, Android SDK (optional), and run a Gradle command'

inputs:
  gradle_command:
    description: 'The gradle command to execute'
    required: true
  java_distribution:
    description: 'The distribution of Java to use'
    required: false
    default: 'zulu'
  java_version:
    description: 'The version of Java to use'
    required: true
  setup_android_sdk:
    description: 'Whether or not to setup the Android SDK (true or false)'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Java Setup
      uses: actions/setup-java@v3.9.0
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
    - name: Setup Android SDK
      if: inputs.setup_android_sdk == 'true'
      uses: android-actions/setup-android@v2
    - name: Run Gradle Command
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ${{ inputs.gradle_command }}
